In [25]:
from keras.applications.mobilenet_v2 import MobileNetV2
import numpy as np
from imageio import imread
from keras.applications.mobilenet_v2 import preprocess_input

In [26]:
model = MobileNetV2(weights = 'imagenet')

In [27]:
model.summary()

Model: "mobilenetv2_1.00_224"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_3 (InputLayer)        [(None, 224, 224, 3)]        0         []                            
                                                                                                  
 Conv1 (Conv2D)              (None, 112, 112, 32)         864       ['input_3[0][0]']             
                                                                                                  
 bn_Conv1 (BatchNormalizati  (None, 112, 112, 32)         128       ['Conv1[0][0]']               
 on)                                                                                              
                                                                                                  
 Conv1_relu (ReLU)           (None, 112, 112, 32)         0         ['bn_Conv1[

 block_3_expand_relu (ReLU)  (None, 56, 56, 144)          0         ['block_3_expand_BN[0][0]']   
                                                                                                  
 block_3_pad (ZeroPadding2D  (None, 57, 57, 144)          0         ['block_3_expand_relu[0][0]'] 
 )                                                                                                
                                                                                                  
 block_3_depthwise (Depthwi  (None, 28, 28, 144)          1296      ['block_3_pad[0][0]']         
 seConv2D)                                                                                        
                                                                                                  
 block_3_depthwise_BN (Batc  (None, 28, 28, 144)          576       ['block_3_depthwise[0][0]']   
 hNormalization)                                                                                  
          

 block_6_depthwise_BN (Batc  (None, 14, 14, 192)          768       ['block_6_depthwise[0][0]']   
 hNormalization)                                                                                  
                                                                                                  
 block_6_depthwise_relu (Re  (None, 14, 14, 192)          0         ['block_6_depthwise_BN[0][0]']
 LU)                                                                                              
                                                                                                  
 block_6_project (Conv2D)    (None, 14, 14, 64)           12288     ['block_6_depthwise_relu[0][0]
                                                                    ']                            
                                                                                                  
 block_6_project_BN (BatchN  (None, 14, 14, 64)           256       ['block_6_project[0][0]']     
 ormalizat

                                                                                                  
 block_9_add (Add)           (None, 14, 14, 64)           0         ['block_8_add[0][0]',         
                                                                     'block_9_project_BN[0][0]']  
                                                                                                  
 block_10_expand (Conv2D)    (None, 14, 14, 384)          24576     ['block_9_add[0][0]']         
                                                                                                  
 block_10_expand_BN (BatchN  (None, 14, 14, 384)          1536      ['block_10_expand[0][0]']     
 ormalization)                                                                                    
                                                                                                  
 block_10_expand_relu (ReLU  (None, 14, 14, 384)          0         ['block_10_expand_BN[0][0]']  
 )        

                                                                                                  
 block_13_expand_relu (ReLU  (None, 14, 14, 576)          0         ['block_13_expand_BN[0][0]']  
 )                                                                                                
                                                                                                  
 block_13_pad (ZeroPadding2  (None, 15, 15, 576)          0         ['block_13_expand_relu[0][0]']
 D)                                                                                               
                                                                                                  
 block_13_depthwise (Depthw  (None, 7, 7, 576)            5184      ['block_13_pad[0][0]']        
 iseConv2D)                                                                                       
                                                                                                  
 block_13_

 iseConv2D)                                                                                       
                                                                                                  
 block_16_depthwise_BN (Bat  (None, 7, 7, 960)            3840      ['block_16_depthwise[0][0]']  
 chNormalization)                                                                                 
                                                                                                  
 block_16_depthwise_relu (R  (None, 7, 7, 960)            0         ['block_16_depthwise_BN[0][0]'
 eLU)                                                               ]                             
                                                                                                  
 block_16_project (Conv2D)   (None, 7, 7, 320)            307200    ['block_16_depthwise_relu[0][0
                                                                    ]']                           
          

In [49]:
import numpy as np
from imageio import imread
data = np.empty((224,224,3))

In [50]:
data= imread('cat.jpeg')
data

C:\Users\rajab\AppData\Local\Temp\ipykernel_16868\2686111430.py:1: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  data= imread('cat.jpeg')


Array([[[ 38,  42,  43],
        [ 38,  42,  43],
        [ 38,  42,  43],
        ...,
        [ 51,  60,  57],
        [ 51,  60,  57],
        [ 51,  60,  57]],

       [[ 38,  42,  43],
        [ 38,  42,  43],
        [ 38,  42,  43],
        ...,
        [ 51,  60,  57],
        [ 51,  60,  57],
        [ 51,  60,  57]],

       [[ 38,  42,  43],
        [ 38,  42,  43],
        [ 38,  42,  43],
        ...,
        [ 51,  60,  57],
        [ 51,  60,  57],
        [ 51,  60,  57]],

       ...,

       [[  4,   5,   7],
        [  4,   5,   7],
        [  4,   5,   7],
        ...,
        [126, 119, 101],
        [124, 117,  99],
        [124, 117,  98]],

       [[  4,   5,   7],
        [  4,   5,   7],
        [  4,   5,   7],
        ...,
        [105,  98,  80],
        [108, 101,  83],
        [118, 111,  92]],

       [[  4,   5,   7],
        [  4,   5,   7],
        [  4,   5,   7],
        ...,
        [102,  95,  77],
        [107, 100,  82],
        [127, 120, 101]]

In [51]:
data = preprocess_input(data)
print(data)

[[[-0.7019608  -0.67058825 -0.6627451 ]
  [-0.7019608  -0.67058825 -0.6627451 ]
  [-0.7019608  -0.67058825 -0.6627451 ]
  ...
  [-0.6        -0.5294118  -0.5529412 ]
  [-0.6        -0.5294118  -0.5529412 ]
  [-0.6        -0.5294118  -0.5529412 ]]

 [[-0.7019608  -0.67058825 -0.6627451 ]
  [-0.7019608  -0.67058825 -0.6627451 ]
  [-0.7019608  -0.67058825 -0.6627451 ]
  ...
  [-0.6        -0.5294118  -0.5529412 ]
  [-0.6        -0.5294118  -0.5529412 ]
  [-0.6        -0.5294118  -0.5529412 ]]

 [[-0.7019608  -0.67058825 -0.6627451 ]
  [-0.7019608  -0.67058825 -0.6627451 ]
  [-0.7019608  -0.67058825 -0.6627451 ]
  ...
  [-0.6        -0.5294118  -0.5529412 ]
  [-0.6        -0.5294118  -0.5529412 ]
  [-0.6        -0.5294118  -0.5529412 ]]

 ...

 [[-0.96862745 -0.9607843  -0.94509804]
  [-0.96862745 -0.9607843  -0.94509804]
  [-0.96862745 -0.9607843  -0.94509804]
  ...
  [-0.01176471 -0.06666666 -0.20784312]
  [-0.02745098 -0.08235294 -0.2235294 ]
  [-0.02745098 -0.08235294 -0.23137254]]

 [

In [52]:
data.min()


-1.0

In [53]:
data.max()

0.9529412

In [55]:
predictions = model.predict(data)
print(predictions)

ValueError: in user code:

    File "C:\Users\rajab\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 2440, in predict_function  *
        return step_function(self, iterator)
    File "C:\Users\rajab\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 2425, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\rajab\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 2413, in run_step  **
        outputs = model.predict_step(data)
    File "C:\Users\rajab\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 2381, in predict_step
        return self(x, training=False)
    File "C:\Users\rajab\anaconda3\Lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\rajab\anaconda3\Lib\site-packages\keras\src\engine\input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "mobilenetv2_1.00_224" is incompatible with the layer: expected shape=(None, 224, 224, 3), found shape=(None, 183, 3)


In [59]:
predict= model.predict(data)
print("predicted class:", preds)

ValueError: in user code:

    File "C:\Users\rajab\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 2440, in predict_function  *
        return step_function(self, iterator)
    File "C:\Users\rajab\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 2425, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\rajab\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 2413, in run_step  **
        outputs = model.predict_step(data)
    File "C:\Users\rajab\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 2381, in predict_step
        return self(x, training=False)
    File "C:\Users\rajab\anaconda3\Lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\rajab\anaconda3\Lib\site-packages\keras\src\engine\input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "mobilenetv2_1.00_224" is incompatible with the layer: expected shape=(None, 224, 224, 3), found shape=(None, 183, 3)
